
Search | Santa Clara County Library | BiblioCommons
 https://sccl.bibliocommons.com/v2/search?query=gradle&searchType=title

Gradle Effective Implementations Guide (eBook) | Santa Clara County Library | BiblioCommons
 https://sccl.bibliocommons.com/item/show/514819118

Gradle Effective Implementations Guide - Second Edition: ProQuest Tech Books
 http://proquest.safaribooksonline.com.rpa.sccl.org/9781784394974

Gradle Recipes for Android: ProQuest Tech Books
 http://proquest.safaribooksonline.com.rpa.sccl.org/9781491947272

